### ISSUE TITLE
How it works with Gminer

### ISSUE THREAD

**Issue by Sysnod** [romslf/Ultimate-Proxy#15]
Can you please explain how to use the smart config with Gminer
sins we have to point the algo in the gminer ;
miner.exe --algo kawpow --server neox.2miners.com:4040 --user

**Comment by Sysnod** [comment]
sins we have to point the algo in the gminer ;
miner.exe --algo kawpow --server neox.2miners.com:4040 --user 
pause

**Comment by romslf** [comment]
Hey,
would you mind either joining the discord [here](https://discord.gg/zWsTZXBYYq) or adding me on telegram [here](https://t.me/romslf) so we can talk about it more easily please ?
