### ISSUE TITLE
Disconnected 

### ISSUE THREAD

**Issue by Sysnod** [romslf/Ultimate-Proxy#16]
After a while, it starts disconnecting and I have to restart the proxy.
![ggg](https://github.com/romslf/Ultimate-Proxy/assets/87899891/09efb3e7-2ba1-43e9-af5c-b1b40305204a)

**Comment by Bitofsin** [comment]
what algo and miner are you running?

**Comment by romslf** [comment]
Hey, can you please provide your proxy configuration as well as what miner you are using please ? So I can better assist you

**Comment by Sysnod** [comment]
I am mining RXD using Gminer with the default configuration and intensity setting,  pool is woolypooly.com. Interestingly, the second time this issue occurred was immediately after the Dev fee stopped.

**Comment by romslf** [comment]
I will take a look today and do some tests, thank you for your patience.
Can you please confirm me that you use the last version (2.2.0.0) ?

**Comment by Sysnod** [comment]
Thank you, yes the last version

**Comment by romslf** [comment]
I'm going to bed right now, it's 2AM here, but I am getting to you as soon as possible. Again, thank you for your patience

**Comment by romslf** [comment]
Meanwhile, can you please make sure that you turn SendStaleShares to false ? This might fix the issue

**Comment by Sysnod** [comment]
SendStaleShares turned to false, I will keep you updated.

**Comment by Sysnod** [comment]
Same problem after SendStaleShares to false

**Comment by romslf** [comment]
Okay, that's a shame, but at least it rules out one possibility.
Please join the discord, so you can send me your logs in private, and I should be able to debug it a lot more easily.

**Comment by Sysnod** [comment]
It seems there was an issue with the pool "woolypooly.com." for now I switched to the pool "vipor.net," and everything is going well so far.

**Comment by romslf** [comment]
Should be fixed in last versions.
