### ISSUE TITLE
Termination of work

### ISSUE THREAD

**Issue by sapperwerewolf** [romslf/Ultimate-Proxy#18]
The proxy works for 10-30 minutes and crashes. [http://joxi.ru/1A50O9xikBPQ82](http://joxi.ru/1A50O9xikBPQ82) 
How to solve this problem?

**Comment by hoangtoro** [comment]
same here

**Comment by romslf** [comment]
Hey, sorry for the late response!

Could you please provide more information about your setup? This includes details like the OS, hardware, proxy configuration, number of workers, etc. Anything that can give me more context would be welcome.

Additionally, if you could add the following lines to your config, it should generate `error.txt` and `log.txt` files containing all the errors. Sending them to me would be really helpful:

```
"Debug": true,
"Log": true,
```

Have you also tried the latest pre-release version? It's available on [Telegram](https://t.me/UltimateProxyChat) or [Discord](https://discord.gg/zWsTZXBYYq)."

**Comment by hoangtoro** [comment]
Thank bro. When I use version 2.4.4, I don't have that problem anymore.

**Comment by romslf** [comment]
Nice, I'm glad to read that.
I'm closing this issue, if you have any questions don't hesitate I'm always here to help !

Happy mining ⛏️🚀
